# https://taskfile.dev

version: "3"

vars:
  # GitHub Actions automatically sets CI=true; use -q there to keep Docker build logs concise.
  DOCKER_COMPOSE_BUILD_QUIET_FLAG: '{{if eq .CI "true"}}-q{{end}}'

tasks:
  default:
    cmd: task -a

  format:
    cmds:
      - ktlint --format
    ignore_error: true

  build:
    cmds:
      - ./gradlew clean
      - ./gradlew uberJar

  tests:
    desc: run gradle tests
    cmd: ./gradlew test

  docker:build:
    cmds:
      - task: build
      - cp build/libs/*.jar docker/compoundnaming.jar
      - docker compose -f docker/docker-compose.yml build {{.DOCKER_COMPOSE_BUILD_QUIET_FLAG}} fuseki

  docker:up:
    cmds:
      - docker compose -f docker/docker-compose.yml up -d

  docker:down:
    cmds:
      - docker compose -f docker/docker-compose.yml down

  docker:clean:
    cmds:
      - docker compose -f docker/docker-compose.yml down -v

  docker:test:
    desc: a docker smoke test
    cmd: ./scripts/docker-test.sh
